### ISSUE TITLE
How to best send command line args to local dynamodb docker container

### ISSUE THREAD

**Issue by dferretti-fig** [aws-samples/aws-sam-java-rest#1]
Sorry if this is the wrong git repo - I couldn't find where the dockerfile for `amazon/dynamodb-local` was being maintained. 

2 questions here:

1. Currently, to send command line args as described here https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html it looks like I need to send the full args to the java process instead of just the args to configure the dynamodb server. So instead of running `docker run -it --rm amazon/dynamodb-local -sharedDb` I need to run `docker run -it --rm amazon/dynamodb-local -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb`
Would it be possible to change the entrypoint/cmd of the dockerfile to handle the java args for you and the user just pass in the extra arguments? I think the more common use case is to just specify the dynamodb args, but if a user wanted to modify the java args they should be able to override the entrypoint in their own `docker run`

2. What directory in the container should I mount if I want to persist the .db file?

**Comment by dferretti-fig** [comment]
After some digging, I found the directory at `/home/dynamodblocal`, so to answer the second question, here is how I currently handle persisting my local dynamodb tables:

`docker run -it --rm -v %cd%:/home/dynamodblocal/data -p 8000:8000 amazon/dynamodb-local -Djava.library.path=./DynamoDBLocal_lib -jar -DynamoDBLocal.jar -sharedDb -dbPath ./data`

**Comment by mrnickel** [comment]
I would also like to mirror @dferretti-fig 's request.

In my case I want to be able to augment my docker-compose.yml file to set the extra args

**Comment by pstephenson02** [comment]
I found this issue having the same question. Would be great if this were a bit easier to pass these args. Thanks!

**Comment by pstephenson02** [comment]
Just a note for anyone reading this as well: @dferretti-fig there is a typo in your comment above: The `-jar` parameter should be: `-jar DynamoDBLocal.jar` not `-jar -DynamoDBLocal.jar` 😎

**Comment by dferretti-fig** [comment]
@pstephenson02 good catch - updated it in the comment 👍

**Comment by hounded** [comment]
Great work @dferretti-fig ! for those that want it I have created a docker-compose file off those findings

```yaml
version: '3'

services:
  dynamo:
    image: amazon/dynamodb-local
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    ports:
      - "8000:8000"
    volumes:
      - <directory>:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
```

**Comment by alecdotico** [comment]
That didn't work for me. The `/home/dynamodblocal/data` folder is owned by `root` user, and the `dynamodblocal` user (which is running the service) cannot create the single databse file under it. This config worked for me:
```yaml
version: '3'
services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
```
